# Generated by Django 4.2.3 on 2023-07-21 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Recruitment_System', '0002_interviews_candidate_alter_application_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In review'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='interviews',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Recruitment_System.application'),
        ),
        migrations.AlterField(
            model_name='interviews',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Recruitment_System.candidate'),
        ),
        migrations.AlterField(
            model_name='interviews',
            name='date_schedule',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interviews',
            name='interviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interviews',
            name='job_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('hired', 'hired')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='interviews',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='interviews',
            name='time_schedule',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interviews',
            name='type',
            field=models.CharField(blank=True, choices=[('phone', 'Phone'), ('in-person', 'In-Person'), ('video', 'Video')], max_length=15, null=True),
        ),
    ]
