# Generated by Django 4.2.3 on 2023-07-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment_System', '0003_alter_application_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviews',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=15, null=True),
        ),
    ]
