# Generated by Django 4.2.3 on 2023-07-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment_System', '0004_alter_interviews_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviews',
            name='slug',
            field=models.SlugField(blank=True, max_length=600, null=True, unique=True),
        ),
    ]
