# Generated by Django 4.2.3 on 2023-07-21 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Recruitment_System', '0006_remove_interviews_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviews',
            name='interviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
