# Generated by Django 4.2.3 on 2023-07-21 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment_System', '0007_alter_interviews_interviewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviews',
            name='status',
        ),
    ]
