# Generated by Django 4.2.3 on 2023-07-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment_System', '0009_remove_interviews_job_status_interviews_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-date_applied']},
        ),
        migrations.AlterModelOptions(
            name='interviews',
            options={'ordering': ['date_schedule']},
        ),
        migrations.AddField(
            model_name='interviews',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
