# Generated by Django 4.2.3 on 2023-07-23 06:41

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment_System', '0010_alter_application_options_alter_interviews_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviews',
            name='note',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
    ]
